### ISSUE TITLE
After a while discord to runescape chats dont send

### ISSUE THREAD

**Issue by Lmctruck30** [aeramos/RuneScape-Discord-Chat-Sync#8]
Unknown cause looking into issue.

**Comment by aeramos** [comment]
After how long of a while? I remember this happened a month ago but it should have been fixed.

**Comment by Lmctruck30** [comment]
not sure been running it for a few hours and noticed the issue.

**Comment by aeramos** [comment]
I'm going to run the bot overnight and try it when I wake up. I might implement a way to take screenshots of the RuneScape window so that debugging problems like this is easier.

**Comment by aeramos** [comment]
I just tried it now, after running it for 12 hours it can no longer send messages in the RuneScape chat, but it does receive them from the RuneScape chat and send them in Discord. I suspect that there is an alert or something on the screen stopping it from sending messages. I'll poke around in the code a bit to see if there's anything obvious and if not then I'll implement a way to take screenshots.

**Comment by Lmctruck30** [comment]
sounds good. thank you.

**Comment by aeramos** [comment]
@Lmctruck30 This bug should be fixed now. I didn't push it to GitHub for a while because I wanted to test it for a day or so, but it should be working now. Thanks for reporting this.

**Comment by aeramos** [comment]
Fixed in commit 4a651ce896de9b0ac76a1e86d78c93cdce327217
